### PR TITLE
Storyboard, Remake, and Final(not finished yet)

### PR DESCRIPTION
**Pull request by KDB000**
Sorry that these are getting turned in so late. My internet has been running at about 900 kbps for the past 2+ weeks.

### CODE REVIEW

**Comment by afreeland** [comment]
It looks like you need to rebase again...there are lots of files with conflicts. Then once you rebase you should be able to push your branch up again `git push origin master -f`

**Comment by KDB000** [comment]
Ok, it says it has no conflicts now on my pull request

**Comment by afreeland** [comment]
@KDB000 but it also shows you editing other students work?
image

**Comment by KDB000** [comment]
Ok, i pulled everything down, rebased, and then pushed everything, so hopefully it should work now.

**Comment by KDB000** [comment]
Ok, i pulled, rebased, and then pushed again, so hopefully everything
should be fixed.

**Comment by afreeland** [comment]
@KDB000 You can look at the top here...shows 182 files have changed? Not sure what is going on with your commits but it shows 155 commits
image

**Comment by afreeland** [comment]
I changed the base of the PR and was able to get it to come down some...but still see one students files have been changed.  May need to check source and verify if that file was deleted or not
image

**Comment by afreeland** [comment]
Looks like that file should *not* be deleted...may want to grab the contents here and make sure it exists?  Did you delete unintentionally?
https://github.com/WVUP/2020_Spring/blob/master/Assignments/Final/DevonDalrymple/js/explore.js


@DevonDalrymple is the code here still valid? This PR show looks to be _deleting_ this file: https://github.com/WVUP/2020_Spring/pull/60/files#diff-8063c4f75ff2ab98342bf7a84dde41a5

**Comment by KDB000** [comment]
yes, it was deleted unintentionally. I have now added that file to my
repository.

**Pull request merged**
